dataset = [["city", "Paris", "Lyon", "Marseille", "Londres", "Berlin", "Rome"],     
        ["pays", "France", "Allemagne", "Italie", "Espagne", "Royaume-Uni", "États-Unis"],
        ["Profession", "Doctor", "Teacher", "Police Officer", "Plumber", "Artist", "Engineer"],
        ["Day of the Week", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        ["Year", "2011", "2012", "2013", "2014", "2015", "2016"],
        ["Month of the Year", "January", "February", "March", "April", "May", "June"],
        ["Mathematical Operation", "Number", "Addition", "Subtraction", "Multiplication", "Division", "Equation"],
        ["Vehicle", "Car", "Motorcycle", "Bicycle", "Truck", "Airplane", "Boat"],
        ["Chemical Element", "Hydrogen", "Oxygen", "Carbon", "Nitrogen", "Iron", "Copper"],
        ['College','Cambridge','Oxford','Harvard','Stanford','Berkeley','Columbia'],
        ["intstrument",'piano','guitar','violin','saxophone','cello','flute'],
        ["Flower", "Rose", "Lily", "Daisy", "Tulip", "Orchid", "Sunflower"],
        ["Jewelry", "Ring", "Necklace", "Bracelet", "Earrings", "Watch", "Brooch"],
        ["School Subject", "Math", "Science", "History", "Geography", "English", "Art"],
        ["Weather", "Sunny", "Rainy", "Cloudy", "Snowy", "Windy", "Stormy"],
        ["Technology", "Computer", "Smartphone", "Tablet", "Smartwatch", "Printer", "Router"],
        ["Clothing", "Shirt", "Pants", "Dress", "Skirt", "Jacket", "Sweater"],
        ["Dessert", "Cake", "Ice Cream", "Pie", "Pudding", "Brownie", "Cookie"],
        ["Tool", "Hammer", "Screwdriver", "Wrench", "Pliers", "Saw", "Drill"],
        ["Bird", "Eagle", "Sparrow", "Parrot", "Owl", "Pigeon", "Crow"],
        ["Fish", "Salmon", "Tuna", "Trout", "Shark", "Goldfish", "Mackerel"],
        ["Book Genre", "Fiction", "Non-fiction", "Mystery", "Fantasy", "Biography", "Science Fiction"],
        ["Holiday", "Christmas", "Easter", "Thanksgiving", "Halloween", "New Year", "Valentine's Day"],
        ["Body Part", "Arm", "Leg", "Head", "Hand", "Foot", "Eye"],
        ["Emotion", "Happy", "Sad", "Angry", "Surprised", "Mad", "Scared"],
        ["Continent", "Africa", "Asia", "Europe", "North America", "South America", "Australia"],
        ]